blank_issues_enabled: false
contact_links:
  - name: Support
    url: https://discord.gg/EwFs3Pp
    about: Please ask and answer questions here
  - name: List a token
    url: https://github.com/xswap/default-token-list#adding-a-token
    about: Any requests to add a token to Xswap should go here
